// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uzM9Vjxk-7G7QZCkMUiPMOUsWdk6aFA',
    appId: '1:463757382457:web:7c0db91c84adba43338ee8',
    messagingSenderId: '463757382457',
    projectId: 'fitpanion-3d8dd',
    authDomain: 'fitpanion-3d8dd.firebaseapp.com',
    storageBucket: 'fitpanion-3d8dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6_Mdb1vwfrKaTNY7JCN5Lisezh7x084',
    appId: '1:463757382457:android:177f9d129649c4f7338ee8',
    messagingSenderId: '463757382457',
    projectId: 'fitpanion-3d8dd',
    storageBucket: 'fitpanion-3d8dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNT35vB7PU_JPTGIA6paMYQRIflJ4upxQ',
    appId: '1:463757382457:ios:5d3a0a59b2beeac6338ee8',
    messagingSenderId: '463757382457',
    projectId: 'fitpanion-3d8dd',
    storageBucket: 'fitpanion-3d8dd.firebasestorage.app',
    iosBundleId: 'com.example.fitpanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNT35vB7PU_JPTGIA6paMYQRIflJ4upxQ',
    appId: '1:463757382457:ios:5d3a0a59b2beeac6338ee8',
    messagingSenderId: '463757382457',
    projectId: 'fitpanion-3d8dd',
    storageBucket: 'fitpanion-3d8dd.firebasestorage.app',
    iosBundleId: 'com.example.fitpanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0uzM9Vjxk-7G7QZCkMUiPMOUsWdk6aFA',
    appId: '1:463757382457:web:f3a94f5d555b99f7338ee8',
    messagingSenderId: '463757382457',
    projectId: 'fitpanion-3d8dd',
    authDomain: 'fitpanion-3d8dd.firebaseapp.com',
    storageBucket: 'fitpanion-3d8dd.firebasestorage.app',
  );
}
